using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;

namespace Naratteu.MewUI.Razor.Analyzers;

/// <summary>
/// Reports an attribute that matches no parameter on the component it is written on. Blazor only
/// discovers this when the component renders, which in a desktop app means a crash on the first
/// frame; the Razor compiler knows the parameter list and emits the attribute name as a plain
/// string, so the same mistake is visible in the generated code at build time.
/// </summary>
[DiagnosticAnalyzer(LanguageNames.CSharp)]
public sealed class UnknownParameterAnalyzer : DiagnosticAnalyzer
{
    public const string DiagnosticId = "MEW001";

    private const string BuilderTypeName = "Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder";

    private static readonly ImmutableHashSet<string> ComponentBaseTypes =
    [
        "Microsoft.AspNetCore.Components.ComponentBase",
        "Naratteu.MewUI.Razor.MewComponentBase",
        "Naratteu.MewUI.Razor.HookComponent",
    ];

    private static readonly DiagnosticDescriptor Rule = new(
        DiagnosticId,
        "Attribute matches no component parameter",
        "'{0}' is not a parameter of {1}",
        "Usage",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true,
        description: "An attribute that matches no parameter compiles cleanly and then throws when "
            + "the component renders. The parameter surface of a MewUI component is generated from "
            + "MewUI's metadata, so a name that looks plausible is not evidence that it exists.");

    public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics => [Rule];

    public override void Initialize(AnalysisContext context)
    {
        // Razor output carries an <auto-generated/> header, which analyzers skip by default.
        context.ConfigureGeneratedCodeAnalysis(
            GeneratedCodeAnalysisFlags.Analyze | GeneratedCodeAnalysisFlags.ReportDiagnostics);
        context.EnableConcurrentExecution();
        context.RegisterSyntaxNodeAction(Analyze, SyntaxKind.InvocationExpression);
    }

    private static void Analyze(SyntaxNodeAnalysisContext context)
    {
        var invocation = (InvocationExpressionSyntax)context.Node;

        if (invocation.Expression is not MemberAccessExpressionSyntax member) return;
        if (member.Expression is not IdentifierNameSyntax builder) return;
        if (member.Name.Identifier.ValueText is not ("AddComponentParameter" or "AddAttribute")) return;
        if (invocation.ArgumentList.Arguments.Count < 2) return;

        if (context.SemanticModel.GetSymbolInfo(invocation, context.CancellationToken).Symbol
            is not IMethodSymbol { ContainingType: { } owner }) return;
        if (owner.ToDisplayString() != BuilderTypeName) return;

        var argument = invocation.ArgumentList.Arguments[1].Expression;
        if (context.SemanticModel.GetConstantValue(argument, context.CancellationToken).Value
            is not string name) return;

        var component = OpenedComponent(
            invocation, builder.Identifier.ValueText, context.SemanticModel, context.CancellationToken);

        if (component is null || !IsComponent(component)) return;
        if (HasParameter(component, name) || CapturesUnmatchedValues(component)) return;

        var value = invocation.ArgumentList.Arguments.Count > 2
            ? invocation.ArgumentList.Arguments[2].Expression
            : argument;

        context.ReportDiagnostic(Diagnostic.Create(Rule, InSource(value, argument), name, component.Name));
    }

    /// <summary>
    /// Points the diagnostic at the .razor file. A generated span inside a <c>#line</c> region is
    /// mapped back by the compiler on its own; the attribute name is not in one, so the nearest
    /// mapping before it stands in — the same element, and in practice the same line.
    /// </summary>
    private static Location InSource(params SyntaxNode[] candidates)
    {
        foreach (var candidate in candidates)
        {
            if (candidate.SyntaxTree.GetMappedLineSpan(candidate.Span).HasMappedPath)
            {
                return candidate.GetLocation();
            }
        }

        var node = candidates[candidates.Length - 1];
        LineSpanDirectiveTriviaSyntax? nearest = null;

        foreach (var directive in node.SyntaxTree.GetRoot()
            .DescendantNodes(descendIntoTrivia: true)
            .OfType<LineSpanDirectiveTriviaSyntax>())
        {
            if (directive.SpanStart > node.SpanStart) break;
            nearest = directive;
        }

        if (nearest is null) return node.GetLocation();

        var position = new LinePosition(
            (int)nearest.Start.Line.Value! - 1,
            (int)nearest.Start.Character.Value! - 1);

        return Location.Create(nearest.File.ValueText, default, new LinePositionSpan(position, position));
    }

    /// <summary>
    /// The component this attribute belongs to: the nearest <c>OpenComponent&lt;T&gt;</c> on the
    /// same builder that is still open. A closed component is skipped along with its opener, which
    /// is what makes sibling components in one block resolve to the right type.
    /// </summary>
    private static INamedTypeSymbol? OpenedComponent(
        SyntaxNode invocation, string builder, SemanticModel model, CancellationToken cancellation)
    {
        if (invocation.FirstAncestorOrSelf<StatementSyntax>() is not { Parent: BlockSyntax block } statement)
        {
            return null;
        }

        var closed = 0;

        for (var i = block.Statements.IndexOf(statement) - 1; i >= 0; i--)
        {
            foreach (var call in Calls(block.Statements[i], builder))
            {
                switch (call.Name.Identifier.ValueText)
                {
                    case "CloseComponent":
                        closed++;
                        break;

                    case "OpenComponent" when closed > 0:
                        closed--;
                        break;

                    case "OpenComponent":
                        return call.Name is GenericNameSyntax { TypeArgumentList.Arguments.Count: 1 } generic
                            ? model.GetSymbolInfo(generic.TypeArgumentList.Arguments[0], cancellation).Symbol
                                as INamedTypeSymbol
                            : null;
                }
            }
        }

        return null;
    }

    /// <summary>Calls on <paramref name="builder"/> inside one statement, last one first.</summary>
    private static IEnumerable<MemberAccessExpressionSyntax> Calls(StatementSyntax statement, string builder)
        => statement.DescendantNodesAndSelf()
            .OfType<InvocationExpressionSyntax>()
            .Select(call => call.Expression)
            .OfType<MemberAccessExpressionSyntax>()
            .Where(member => member.Expression is IdentifierNameSyntax name
                && name.Identifier.ValueText == builder)
            .Reverse();

    private static bool IsComponent(INamedTypeSymbol component)
    {
        for (var type = component; type is not null; type = type.BaseType)
        {
            if (ComponentBaseTypes.Contains(type.ToDisplayString())) return true;
        }

        return false;
    }

    private static bool HasParameter(INamedTypeSymbol component, string name)
        => Properties(component).Any(property => property.Name == name && IsParameter(property));

    private static bool CapturesUnmatchedValues(INamedTypeSymbol component) => Properties(component)
        .SelectMany(property => property.GetAttributes())
        .Any(attribute => attribute.NamedArguments
            .Any(argument => argument.Key == "CaptureUnmatchedValues" && argument.Value.Value is true));

    private static IEnumerable<IPropertySymbol> Properties(INamedTypeSymbol component)
    {
        for (var type = component; type is not null; type = type.BaseType)
        {
            foreach (var property in type.GetMembers().OfType<IPropertySymbol>())
            {
                if (property.DeclaredAccessibility == Accessibility.Public) yield return property;
            }
        }
    }

    private static bool IsParameter(IPropertySymbol property) => property.GetAttributes()
        .Any(attribute => attribute.AttributeClass?.Name.EndsWith("ParameterAttribute") is true);
}
